image: node:latest

cache:
  paths:
    - node_modules/

before_script:
  - npm install

stages:
  - build

job_gulp:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist
  when: manual
